package WebService::ZombiesRun;
use v5.010;
use strict;
use warnings;
use autodie;
use Moo;
use JSON::Any;
use WWW::Mechanize;
use Data::Dumper;

our $DEBUG = 1;

use constant API_BASE => 'https://www.zombiesrungame.com/api/v3';

# ABSTRACT: Access run information from the Zombies, Run! game

# VERSION: Generated by DZP::OurPkg:Version

has player => (is => 'rw');
has agent  => (is => 'lazy');
has json   => (is => 'lazy');

sub _build_agent { return WWW::Mechanize->new; }
sub _build_json  { return JSON::Any->new;      }

sub runs {
    my ($self) = @_;

    say Dumper $self->_fetch_user_path("manifest");
}

sub _fetch_user_path {
    my ($self, $path) = @_;

    my $user = $self->player;

    # Yes, this needs a slash before the ? for it to work
    my $call = join("/", API_BASE, "user/$user", $path, "?format=json");

    warn "Calling $call\n" if $DEBUG;
    $self->agent->get($call);

    return $self->json->decode( $self->agent->content );
}

=for Pod::Coverage BUILD DEMOLISH

=cut

1;
